service: myService

plugins:
  - serverless-dotenv-plugin

path: .env


provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_HOST: ${env:DB_HOST}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_PASSWORD: ${env:DB_PASSWORD}
    SECRET: ${env:SECRET}
    PORT: ${env:PORT}

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'